security:
    providers:
        in_memory:
            memory:
                users:
                    username:
                        password: $2y$12$g/55Vl2skmbseun7L0tdOue3mkMyHDfC3Y2591xqGHbemx5TNz.7m
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: re_login
                check_path: re_login
                default_target_path: re_login

    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
