re_download:
    path:     /dl/{file}
    defaults: { _controller: MainBundle:Default:sendFile }

re_service:
    path:     /service
    defaults: { _controller: MainBundle:Default:service }

re_logout:
    path:     /logout
    defaults: { _controller: MainBundle:Security:logout }

re_login:
    path:     /login
    defaults: { _controller: MainBundle:Security:login }

re_user:
    path:     /user
    defaults: { _controller: MainBundle:Security:user }

re_admin:
    path:     /admin
    defaults: { _controller: MainBundle:Security:admin }

re_main:
    path:     /site
    defaults: { _controller: MainBundle:Default:index }

re_contact:
    path:     /{_locale}/contact
    defaults: { _controller: MainBundle:Default:contact }
    requirements:
        _locale: en|fr

re_test:
    path:     /test
    defaults: { _controller: MainBundle:Default:test }
